name: example
description: intl_manager example.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

  intl: '>=0.15.7'
  intl_translation: ^0.17.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_manager:
    path: ../ #in real project you need depend on dart pub repository(intl_manager: ^0.0.2)

flutter:
  uses-material-design: true